name: Deploy Expo App

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./mathematador-app
        run: npm install

      - name: Build the app
        working-directory: ./mathematador-app
        run: npm run build

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy dist folder to server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        working-directory: ./mathematador-app
        run: |
          sshpass -e rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./dist/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: Restart PM2 process
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            pm2 restart ${{ secrets.PM2_APP_NAME }} || pm2 start ${{ secrets.DEPLOY_PATH }}/index.js --name ${{ secrets.PM2_APP_NAME }}
          "
