/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { CosmeticType } from './cosmeticType';
import type { Id } from './id';

export interface Cosmetic {
  id?: Id;
  name?: string;
  type?: CosmeticType;
  price?: number;
  assetId?: string;
  requiredLevel?: number;
}
