/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

export interface CredentialsUsername {
  username?: string;
}
