/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hibrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { CredentialsEmail } from "./credentialsEmail";
import type { CredentialsPassword } from "./credentialsPassword";

export type Credentials = CredentialsEmail &
  CredentialsPassword &
  Required<Pick<CredentialsEmail & CredentialsPassword, "email" | "password">>;
