/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hibrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

export type ExquationType = (typeof ExquationType)[keyof typeof ExquationType];

export const ExquationType = {
  entry: "entry",
  result: "result",
  operator: "operator",
} as const;
