/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hibrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { CredentialsPassword } from "./credentialsPassword";
import type { ForgottenToken } from "./forgottenToken";

export type ForgottenCredentials = CredentialsPassword &
  ForgottenToken &
  Required<
    Pick<CredentialsPassword & ForgottenToken, "password" | "tokenForgotten">
  >;
