/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hibrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { Challenge } from "./challenge";

export interface GameOperationProgress {
  level?: number;
  xp?: number;
  Challenges?: Challenge[];
}
