/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

export type UserSettingsGetHistoryParams = {
/**
 * Opaque pagination cursor from a previous response's nextCursor - omit for the first page
 */
cursor?: string;
/**
 * Max rows to return (default 50, capped at 200)
 */
limit?: string;
};
