/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { ChallengeRequest } from './challengeRequest';
import type { ChallengeResultRequest } from './challengeResultRequest';
import type { Exercise } from './exercise';
import type { Id } from './id';

export type Challenge = ChallengeRequest & {
  result?: ChallengeResultRequest;
  id?: Id;
  exercises?: Exercise[];
  maxTime?: number;
  xpOnSuccess?: number;
  xpOnFailure?: number;
  coinsOnSuccess?: number;
  coinsOnFailure?: number;
  coins?: number;
  allowedMistakes?: number;
};
