/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { Id } from "./id";
import type { Minigame } from "./minigame";
import type { OperationId } from "./operationId";

export type ChallengeRequest = {
  operationId?: OperationId;
  minigame?: Minigame;
  userId?: Id;
  challengeId?: Id;
};
