/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { Id } from "./id";

export type CosmeticsBuyBody = {
  cosmeticId: Id;
};
