/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

export type CosmeticType = typeof CosmeticType[keyof typeof CosmeticType];


export const CosmeticType = {
  cape: 'cape',
  suit: 'suit',
  flare: 'flare',
} as const;
