/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { GameOperationProgress } from './gameOperationProgress';
import type { Id } from './id';
import type { MinigameProgress } from './minigameProgress';

export type GameProgress = {
  level?: number;
  xp?: number;
  coins?: number;
  operations?: GameOperationProgress[];
  purchasedCosmetics?: Id[];
  equippedCape?: Id | null;
  equippedSuit?: Id | null;
  equippedFlare?: Id | null;
  minigameProgress?: MinigameProgress[];
};
