/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

export * from './challenge';
export * from './challengeRequest';
export * from './challengeResultRequest';
export * from './cosmetic';
export * from './cosmeticsBuyBody';
export * from './cosmeticsEquipBody';
export * from './cosmeticType';
export * from './credentials';
export * from './credentialsEmail';
export * from './credentialsPassword';
export * from './equationType';
export * from './exercise';
export * from './forgottenCredentials';
export * from './forgottenToken';
export * from './gameOperationProgress';
export * from './gameProgress';
export * from './id';
export * from './minigame';
export * from './minigameProgress';
export * from './operationId';
export * from './subscription';
export * from './subscriptionCreate';
export * from './subscriptionType';
export * from './userProfile';
