/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { Minigame } from "./minigame";

export type MinigameProgress = {
  minigameId?: Minigame;
  level?: number;
  xp?: number;
};
