/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

export type OperationId = (typeof OperationId)[keyof typeof OperationId];

export const OperationId = {
  addition: "addition",
  subtraction: "subtraction",
  multiplication: "multiplication",
  division: "division"
} as const;
