/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { CredentialsEmail } from './credentialsEmail';
import type { CredentialsPassword } from './credentialsPassword';
import type { CredentialsUsername } from './credentialsUsername';

export type RegisterCredentials = CredentialsEmail & CredentialsPassword & CredentialsUsername & Required<Pick<CredentialsEmail & CredentialsPassword & CredentialsUsername, 'password' | 'username'>>;
