/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

export type SubscriptionType = (typeof SubscriptionType)[keyof typeof SubscriptionType];

export const SubscriptionType = {
  addsFree: "addsFree",
  full: "full"
} as const;
