/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

export type UserSettingKey = typeof UserSettingKey[keyof typeof UserSettingKey];


export const UserSettingKey = {
  ads_consent: 'ads_consent',
  gdpr_consent: 'gdpr_consent',
} as const;
