/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { UserSettingKey } from './userSettingKey';

export type UserSetting = {
  settingKey: UserSettingKey;
  settingValue: string;
  changedAt: string;
  deviceId: string;
};
