/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import type { UserSetting } from './userSetting';

export type UserSettingsHistoryPage = {
  items: UserSetting[];
  /** @nullable */
  nextCursor: string | null;
};
