/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Challenge,
  ChallengeRequest,
  ChallengeResultRequest,
  CheckEmailResponse,
  ConsentRecord,
  Cosmetic,
  CosmeticsBuyBody,
  CosmeticsEquipBody,
  Credentials,
  CredentialsEmail,
  CredentialsPassword,
  GameProgress,
  GoogleIdToken,
  RegisterCredentials,
  Subscription,
  SubscriptionCreate,
  UserProfile
} from './model';

import { customInstance } from '../utils/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type userForgottenResponse201 = {
  data: void
  status: 201
}

export type userForgottenResponseSuccess = (userForgottenResponse201) & {
  headers: Headers;
};
;

export type userForgottenResponse = (userForgottenResponseSuccess)

export const getUserForgottenUrl = () => {




  return `/user/forgotten`
}

export const userForgotten = async (credentialsEmail: CredentialsEmail, options?: Parameters<typeof customInstance>[1]): Promise<userForgottenResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<userForgottenResponse>(getUserForgottenUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(credentialsEmail)
  }
);}





export const getUserForgottenMutationKey = () => ['userForgotten'] as const;

export const getUserForgottenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userForgotten>>, TError,UserForgottenMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userForgotten>>, TError,UserForgottenMutationVariables, TContext> => {

const mutationKey = getUserForgottenMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userForgotten>>, UserForgottenMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  userForgotten(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserForgottenMutationResult = NonNullable<Awaited<ReturnType<typeof userForgotten>>>
    export type UserForgottenMutationBody = CredentialsEmail
    export type UserForgottenMutationError = unknown
    export type UserForgottenMutationVariables = {data: CredentialsEmail}

    export const useUserForgotten = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userForgotten>>, TError,UserForgottenMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userForgotten>>,
        TError,
        UserForgottenMutationVariables,
        TContext
      > => {
      return useMutation(getUserForgottenMutationOptions(options));
    }

export type userLoginResponse200 = {
  data: UserProfile
  status: 200
}

export type userLoginResponseSuccess = (userLoginResponse200) & {
  headers: Headers;
};
;

export type userLoginResponse = (userLoginResponseSuccess)

export const getUserLoginUrl = () => {




  return `/user/login`
}

/**
 * @summary check the credentials and login
 */
export const userLogin = async (credentials: Credentials, options?: Parameters<typeof customInstance>[1]): Promise<userLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<userLoginResponse>(getUserLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(credentials)
  }
);}





export const getUserLoginMutationKey = () => ['userLogin'] as const;

export const getUserLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userLogin>>, TError,UserLoginMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userLogin>>, TError,UserLoginMutationVariables, TContext> => {

const mutationKey = getUserLoginMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userLogin>>, UserLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  userLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserLoginMutationResult = NonNullable<Awaited<ReturnType<typeof userLogin>>>
    export type UserLoginMutationBody = Credentials
    export type UserLoginMutationError = unknown
    export type UserLoginMutationVariables = {data: Credentials}

    /**
 * @summary check the credentials and login
 */
export const useUserLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userLogin>>, TError,UserLoginMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userLogin>>,
        TError,
        UserLoginMutationVariables,
        TContext
      > => {
      return useMutation(getUserLoginMutationOptions(options));
    }

export type userLoginPasswordResponse200 = {
  data: UserProfile
  status: 200
}

export type userLoginPasswordResponseSuccess = (userLoginPasswordResponse200) & {
  headers: Headers;
};
;

export type userLoginPasswordResponse = (userLoginPasswordResponseSuccess)

export const getUserLoginPasswordUrl = () => {




  return `/user/login`
}

/**
 * @summary submit new password after forgotten
 */
export const userLoginPassword = async (credentialsPassword: CredentialsPassword, options?: Parameters<typeof customInstance>[1]): Promise<userLoginPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<userLoginPasswordResponse>(getUserLoginPasswordUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(credentialsPassword)
  }
);}





export const getUserLoginPasswordMutationKey = () => ['userLoginPassword'] as const;

export const getUserLoginPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userLoginPassword>>, TError,UserLoginPasswordMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userLoginPassword>>, TError,UserLoginPasswordMutationVariables, TContext> => {

const mutationKey = getUserLoginPasswordMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userLoginPassword>>, UserLoginPasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  userLoginPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserLoginPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof userLoginPassword>>>
    export type UserLoginPasswordMutationBody = CredentialsPassword
    export type UserLoginPasswordMutationError = unknown
    export type UserLoginPasswordMutationVariables = {data: CredentialsPassword}

    /**
 * @summary submit new password after forgotten
 */
export const useUserLoginPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userLoginPassword>>, TError,UserLoginPasswordMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userLoginPassword>>,
        TError,
        UserLoginPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getUserLoginPasswordMutationOptions(options));
    }

export type userRegisterResponse200 = {
  data: UserProfile
  status: 200
}

export type userRegisterResponseSuccess = (userRegisterResponse200) & {
  headers: Headers;
};
;

export type userRegisterResponse = (userRegisterResponseSuccess)

export const getUserRegisterUrl = () => {




  return `/user/register`
}

/**
 * @summary Register a new user
 */
export const userRegister = async (registerCredentials: RegisterCredentials, options?: Parameters<typeof customInstance>[1]): Promise<userRegisterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<userRegisterResponse>(getUserRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerCredentials)
  }
);}





export const getUserRegisterMutationKey = () => ['userRegister'] as const;

export const getUserRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userRegister>>, TError,UserRegisterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userRegister>>, TError,UserRegisterMutationVariables, TContext> => {

const mutationKey = getUserRegisterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userRegister>>, UserRegisterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  userRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof userRegister>>>
    export type UserRegisterMutationBody = RegisterCredentials
    export type UserRegisterMutationError = unknown
    export type UserRegisterMutationVariables = {data: RegisterCredentials}

    /**
 * @summary Register a new user
 */
export const useUserRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userRegister>>, TError,UserRegisterMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userRegister>>,
        TError,
        UserRegisterMutationVariables,
        TContext
      > => {
      return useMutation(getUserRegisterMutationOptions(options));
    }

export type userGoogleLoginResponse200 = {
  data: UserProfile
  status: 200
}

export type userGoogleLoginResponseSuccess = (userGoogleLoginResponse200) & {
  headers: Headers;
};
;

export type userGoogleLoginResponse = (userGoogleLoginResponseSuccess)

export const getUserGoogleLoginUrl = () => {




  return `/user/google-login`
}

/**
 * @summary Sign in (or register/link) via a verified Google ID token
 */
export const userGoogleLogin = async (googleIdToken: GoogleIdToken, options?: Parameters<typeof customInstance>[1]): Promise<userGoogleLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<userGoogleLoginResponse>(getUserGoogleLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(googleIdToken)
  }
);}





export const getUserGoogleLoginMutationKey = () => ['userGoogleLogin'] as const;

export const getUserGoogleLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userGoogleLogin>>, TError,UserGoogleLoginMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userGoogleLogin>>, TError,UserGoogleLoginMutationVariables, TContext> => {

const mutationKey = getUserGoogleLoginMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userGoogleLogin>>, UserGoogleLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  userGoogleLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserGoogleLoginMutationResult = NonNullable<Awaited<ReturnType<typeof userGoogleLogin>>>
    export type UserGoogleLoginMutationBody = GoogleIdToken
    export type UserGoogleLoginMutationError = unknown
    export type UserGoogleLoginMutationVariables = {data: GoogleIdToken}

    /**
 * @summary Sign in (or register/link) via a verified Google ID token
 */
export const useUserGoogleLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userGoogleLogin>>, TError,UserGoogleLoginMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userGoogleLogin>>,
        TError,
        UserGoogleLoginMutationVariables,
        TContext
      > => {
      return useMutation(getUserGoogleLoginMutationOptions(options));
    }

export type userCheckEmailResponse200 = {
  data: CheckEmailResponse
  status: 200
}

export type userCheckEmailResponseSuccess = (userCheckEmailResponse200) & {
  headers: Headers;
};
;

export type userCheckEmailResponse = (userCheckEmailResponseSuccess)

export const getUserCheckEmailUrl = () => {




  return `/user/check-email`
}

/**
 * @summary Check whether an email is already registered
 */
export const userCheckEmail = async (credentialsEmail: CredentialsEmail, options?: Parameters<typeof customInstance>[1]): Promise<userCheckEmailResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<userCheckEmailResponse>(getUserCheckEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(credentialsEmail)
  }
);}





export const getUserCheckEmailMutationKey = () => ['userCheckEmail'] as const;

export const getUserCheckEmailMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userCheckEmail>>, TError,UserCheckEmailMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userCheckEmail>>, TError,UserCheckEmailMutationVariables, TContext> => {

const mutationKey = getUserCheckEmailMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userCheckEmail>>, UserCheckEmailMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  userCheckEmail(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserCheckEmailMutationResult = NonNullable<Awaited<ReturnType<typeof userCheckEmail>>>
    export type UserCheckEmailMutationBody = CredentialsEmail
    export type UserCheckEmailMutationError = unknown
    export type UserCheckEmailMutationVariables = {data: CredentialsEmail}

    /**
 * @summary Check whether an email is already registered
 */
export const useUserCheckEmail = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userCheckEmail>>, TError,UserCheckEmailMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userCheckEmail>>,
        TError,
        UserCheckEmailMutationVariables,
        TContext
      > => {
      return useMutation(getUserCheckEmailMutationOptions(options));
    }

export type userConsentRecordResponse200 = {
  data: ConsentRecord
  status: 200
}

export type userConsentRecordResponseSuccess = (userConsentRecordResponse200) & {
  headers: Headers;
};
;

export type userConsentRecordResponse = (userConsentRecordResponseSuccess)

export const getUserConsentRecordUrl = () => {




  return `/user/consent`
}

/**
 * @summary Persist the device-recorded, pre-login consent against the now-authenticated account (idempotent - the first consent on file always wins)
 */
export const userConsentRecord = async (consentRecord: ConsentRecord, options?: Parameters<typeof customInstance>[1]): Promise<userConsentRecordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<userConsentRecordResponse>(getUserConsentRecordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(consentRecord)
  }
);}





export const getUserConsentRecordMutationKey = () => ['userConsentRecord'] as const;

export const getUserConsentRecordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userConsentRecord>>, TError,UserConsentRecordMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userConsentRecord>>, TError,UserConsentRecordMutationVariables, TContext> => {

const mutationKey = getUserConsentRecordMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userConsentRecord>>, UserConsentRecordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  userConsentRecord(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserConsentRecordMutationResult = NonNullable<Awaited<ReturnType<typeof userConsentRecord>>>
    export type UserConsentRecordMutationBody = ConsentRecord
    export type UserConsentRecordMutationError = unknown
    export type UserConsentRecordMutationVariables = {data: ConsentRecord}

    /**
 * @summary Persist the device-recorded, pre-login consent against the now-authenticated account (idempotent - the first consent on file always wins)
 */
export const useUserConsentRecord = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userConsentRecord>>, TError,UserConsentRecordMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userConsentRecord>>,
        TError,
        UserConsentRecordMutationVariables,
        TContext
      > => {
      return useMutation(getUserConsentRecordMutationOptions(options));
    }

export type userForgottenPasswordResponse201 = {
  data: void
  status: 201
}

export type userForgottenPasswordResponseSuccess = (userForgottenPasswordResponse201) & {
  headers: Headers;
};
;

export type userForgottenPasswordResponse = (userForgottenPasswordResponseSuccess)

export const getUserForgottenPasswordUrl = () => {




  return `/user/forgotten-password`
}

/**
 * @summary Send forgotten password email
 */
export const userForgottenPassword = async (credentialsEmail: CredentialsEmail, options?: Parameters<typeof customInstance>[1]): Promise<userForgottenPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<userForgottenPasswordResponse>(getUserForgottenPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(credentialsEmail)
  }
);}





export const getUserForgottenPasswordMutationKey = () => ['userForgottenPassword'] as const;

export const getUserForgottenPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userForgottenPassword>>, TError,UserForgottenPasswordMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userForgottenPassword>>, TError,UserForgottenPasswordMutationVariables, TContext> => {

const mutationKey = getUserForgottenPasswordMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userForgottenPassword>>, UserForgottenPasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  userForgottenPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserForgottenPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof userForgottenPassword>>>
    export type UserForgottenPasswordMutationBody = CredentialsEmail
    export type UserForgottenPasswordMutationError = unknown
    export type UserForgottenPasswordMutationVariables = {data: CredentialsEmail}

    /**
 * @summary Send forgotten password email
 */
export const useUserForgottenPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userForgottenPassword>>, TError,UserForgottenPasswordMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userForgottenPassword>>,
        TError,
        UserForgottenPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getUserForgottenPasswordMutationOptions(options));
    }

export type challengeStartNewResponse200 = {
  data: Challenge
  status: 200
}

export type challengeStartNewResponseSuccess = (challengeStartNewResponse200) & {
  headers: Headers;
};
;

export type challengeStartNewResponse = (challengeStartNewResponseSuccess)

export const getChallengeStartNewUrl = (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',) => {




  return `/challenges/${operationId}`
}

/**
 * @summary Create a new game
 */
export const challengeStartNew = async (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',
    challengeRequest: ChallengeRequest, options?: Parameters<typeof customInstance>[1]): Promise<challengeStartNewResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<challengeStartNewResponse>(getChallengeStartNewUrl(operationId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(challengeRequest)
  }
);}





export const getChallengeStartNewMutationKey = () => ['challengeStartNew'] as const;

export const getChallengeStartNewMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof challengeStartNew>>, TError,ChallengeStartNewMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof challengeStartNew>>, TError,ChallengeStartNewMutationVariables, TContext> => {

const mutationKey = getChallengeStartNewMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof challengeStartNew>>, ChallengeStartNewMutationVariables> = (props) => {
          const {operationId,data} = props ?? {};

          return  challengeStartNew(operationId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChallengeStartNewMutationResult = NonNullable<Awaited<ReturnType<typeof challengeStartNew>>>
    export type ChallengeStartNewMutationBody = ChallengeRequest
    export type ChallengeStartNewMutationError = unknown
    export type ChallengeStartNewMutationVariables = {operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge';data: ChallengeRequest}

    /**
 * @summary Create a new game
 */
export const useChallengeStartNew = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof challengeStartNew>>, TError,ChallengeStartNewMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof challengeStartNew>>,
        TError,
        ChallengeStartNewMutationVariables,
        TContext
      > => {
      return useMutation(getChallengeStartNewMutationOptions(options));
    }

export type challengeGetAllResponse200 = {
  data: Challenge[]
  status: 200
}

export type challengeGetAllResponseSuccess = (challengeGetAllResponse200) & {
  headers: Headers;
};
;

export type challengeGetAllResponse = (challengeGetAllResponseSuccess)

export const getChallengeGetAllUrl = (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',) => {




  return `/challenges/${operationId}`
}

/**
 * @summary Get all user challenges
 */
export const challengeGetAll = async (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge', options?: Parameters<typeof customInstance>[1]): Promise<challengeGetAllResponse> => {

  return customInstance<challengeGetAllResponse>(getChallengeGetAllUrl(operationId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getChallengeGetAllQueryKey = (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',) => {
    return [
    `/challenges/${operationId}`
    ] as const;
    }


export const getChallengeGetAllQueryOptions = <TData = Awaited<ReturnType<typeof challengeGetAll>>, TError = unknown>(operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge', options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof challengeGetAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChallengeGetAllQueryKey(operationId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof challengeGetAll>>> = ({ signal }) => challengeGetAll(operationId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: operationId !== null && operationId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof challengeGetAll>>, TError, TData> & { queryKey: QueryKey }
}

export type ChallengeGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof challengeGetAll>>>
export type ChallengeGetAllQueryError = unknown


/**
 * @summary Get all user challenges
 */

export function useChallengeGetAll<TData = Awaited<ReturnType<typeof challengeGetAll>>, TError = unknown>(
 operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge', options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof challengeGetAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getChallengeGetAllQueryOptions(operationId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type challengeGetResponse200 = {
  data: Challenge
  status: 200
}

export type challengeGetResponseSuccess = (challengeGetResponse200) & {
  headers: Headers;
};
;

export type challengeGetResponse = (challengeGetResponseSuccess)

export const getChallengeGetUrl = (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',
    id: string,) => {




  return `/challenges/${operationId}/${id}`
}

/**
 * @summary Get challenge by id
 */
export const challengeGet = async (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',
    id: string, options?: Parameters<typeof customInstance>[1]): Promise<challengeGetResponse> => {

  return customInstance<challengeGetResponse>(getChallengeGetUrl(operationId,id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getChallengeGetQueryKey = (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',
    id: string,) => {
    return [
    `/challenges/${operationId}/${id}`
    ] as const;
    }


export const getChallengeGetQueryOptions = <TData = Awaited<ReturnType<typeof challengeGet>>, TError = unknown>(operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof challengeGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChallengeGetQueryKey(operationId,id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof challengeGet>>> = ({ signal }) => challengeGet(operationId,id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: operationId !== null && operationId !== undefined && id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof challengeGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ChallengeGetQueryResult = NonNullable<Awaited<ReturnType<typeof challengeGet>>>
export type ChallengeGetQueryError = unknown


/**
 * @summary Get challenge by id
 */

export function useChallengeGet<TData = Awaited<ReturnType<typeof challengeGet>>, TError = unknown>(
 operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof challengeGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getChallengeGetQueryOptions(operationId,id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type challengeUpdateResultResponse200 = {
  data: GameProgress
  status: 200
}

export type challengeUpdateResultResponseSuccess = (challengeUpdateResultResponse200) & {
  headers: Headers;
};
;

export type challengeUpdateResultResponse = (challengeUpdateResultResponseSuccess)

export const getChallengeUpdateResultUrl = (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',
    id: string,) => {




  return `/challenges/${operationId}/${id}`
}

/**
 * @summary Update challenge items
 */
export const challengeUpdateResult = async (operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge',
    id: string,
    challengeResultRequest: ChallengeResultRequest, options?: Parameters<typeof customInstance>[1]): Promise<challengeUpdateResultResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<challengeUpdateResultResponse>(getChallengeUpdateResultUrl(operationId,id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(challengeResultRequest)
  }
);}





export const getChallengeUpdateResultMutationKey = () => ['challengeUpdateResult'] as const;

export const getChallengeUpdateResultMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof challengeUpdateResult>>, TError,ChallengeUpdateResultMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof challengeUpdateResult>>, TError,ChallengeUpdateResultMutationVariables, TContext> => {

const mutationKey = getChallengeUpdateResultMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof challengeUpdateResult>>, ChallengeUpdateResultMutationVariables> = (props) => {
          const {operationId,id,data} = props ?? {};

          return  challengeUpdateResult(operationId,id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChallengeUpdateResultMutationResult = NonNullable<Awaited<ReturnType<typeof challengeUpdateResult>>>
    export type ChallengeUpdateResultMutationBody = ChallengeResultRequest
    export type ChallengeUpdateResultMutationError = unknown
    export type ChallengeUpdateResultMutationVariables = {operationId: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'gauntlet' | 'daily_challenge';id: string;data: ChallengeResultRequest}

    /**
 * @summary Update challenge items
 */
export const useChallengeUpdateResult = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof challengeUpdateResult>>, TError,ChallengeUpdateResultMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof challengeUpdateResult>>,
        TError,
        ChallengeUpdateResultMutationVariables,
        TContext
      > => {
      return useMutation(getChallengeUpdateResultMutationOptions(options));
    }

export type subscriptionUpdateResponse200 = {
  data: Subscription
  status: 200
}

export type subscriptionUpdateResponseSuccess = (subscriptionUpdateResponse200) & {
  headers: Headers;
};
;

export type subscriptionUpdateResponse = (subscriptionUpdateResponseSuccess)

export const getSubscriptionUpdateUrl = () => {




  return `/subscriptions`
}

/**
 * @summary Add new subscription
 */
export const subscriptionUpdate = async (subscriptionCreate: SubscriptionCreate, options?: Parameters<typeof customInstance>[1]): Promise<subscriptionUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<subscriptionUpdateResponse>(getSubscriptionUpdateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(subscriptionCreate)
  }
);}





export const getSubscriptionUpdateMutationKey = () => ['subscriptionUpdate'] as const;

export const getSubscriptionUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscriptionUpdate>>, TError,SubscriptionUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof subscriptionUpdate>>, TError,SubscriptionUpdateMutationVariables, TContext> => {

const mutationKey = getSubscriptionUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscriptionUpdate>>, SubscriptionUpdateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  subscriptionUpdate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscriptionUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof subscriptionUpdate>>>
    export type SubscriptionUpdateMutationBody = SubscriptionCreate
    export type SubscriptionUpdateMutationError = unknown
    export type SubscriptionUpdateMutationVariables = {data: SubscriptionCreate}

    /**
 * @summary Add new subscription
 */
export const useSubscriptionUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscriptionUpdate>>, TError,SubscriptionUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof subscriptionUpdate>>,
        TError,
        SubscriptionUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getSubscriptionUpdateMutationOptions(options));
    }

export type subscriptionCancelImmediatelyResponse200 = {
  data: void
  status: 200
}

export type subscriptionCancelImmediatelyResponseSuccess = (subscriptionCancelImmediatelyResponse200) & {
  headers: Headers;
};
;

export type subscriptionCancelImmediatelyResponse = (subscriptionCancelImmediatelyResponseSuccess)

export const getSubscriptionCancelImmediatelyUrl = () => {




  return `/subscriptions`
}

/**
 * @summary Remove subscription
 */
export const subscriptionCancelImmediately = async ( options?: Parameters<typeof customInstance>[1]): Promise<subscriptionCancelImmediatelyResponse> => {

  return customInstance<subscriptionCancelImmediatelyResponse>(getSubscriptionCancelImmediatelyUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getSubscriptionCancelImmediatelyMutationKey = () => ['subscriptionCancelImmediately'] as const;

export const getSubscriptionCancelImmediatelyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscriptionCancelImmediately>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof subscriptionCancelImmediately>>, TError,void, TContext> => {

const mutationKey = getSubscriptionCancelImmediatelyMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscriptionCancelImmediately>>, void> = () => {


          return  subscriptionCancelImmediately(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscriptionCancelImmediatelyMutationResult = NonNullable<Awaited<ReturnType<typeof subscriptionCancelImmediately>>>

    export type SubscriptionCancelImmediatelyMutationError = unknown


    /**
 * @summary Remove subscription
 */
export const useSubscriptionCancelImmediately = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscriptionCancelImmediately>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof subscriptionCancelImmediately>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSubscriptionCancelImmediatelyMutationOptions(options));
    }

export type gameProgressResponse200 = {
  data: GameProgress
  status: 200
}

export type gameProgressResponseSuccess = (gameProgressResponse200) & {
  headers: Headers;
};
;

export type gameProgressResponse = (gameProgressResponseSuccess)

export const getGameProgressUrl = () => {




  return `/game/progress`
}

/**
 * @summary Get game status
 */
export const gameProgress = async ( options?: Parameters<typeof customInstance>[1]): Promise<gameProgressResponse> => {

  return customInstance<gameProgressResponse>(getGameProgressUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGameProgressQueryKey = () => {
    return [
    `/game/progress`
    ] as const;
    }


export const getGameProgressQueryOptions = <TData = Awaited<ReturnType<typeof gameProgress>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof gameProgress>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGameProgressQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof gameProgress>>> = ({ signal }) => gameProgress({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gameProgress>>, TError, TData> & { queryKey: QueryKey }
}

export type GameProgressQueryResult = NonNullable<Awaited<ReturnType<typeof gameProgress>>>
export type GameProgressQueryError = unknown


/**
 * @summary Get game status
 */

export function useGameProgress<TData = Awaited<ReturnType<typeof gameProgress>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof gameProgress>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGameProgressQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type cosmeticsGetAllResponse200 = {
  data: Cosmetic[]
  status: 200
}

export type cosmeticsGetAllResponseSuccess = (cosmeticsGetAllResponse200) & {
  headers: Headers;
};
;

export type cosmeticsGetAllResponse = (cosmeticsGetAllResponseSuccess)

export const getCosmeticsGetAllUrl = () => {




  return `/cosmetics`
}

/**
 * @summary Retrieve all available cosmetics in the shop
 */
export const cosmeticsGetAll = async ( options?: Parameters<typeof customInstance>[1]): Promise<cosmeticsGetAllResponse> => {

  return customInstance<cosmeticsGetAllResponse>(getCosmeticsGetAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCosmeticsGetAllQueryKey = () => {
    return [
    `/cosmetics`
    ] as const;
    }


export const getCosmeticsGetAllQueryOptions = <TData = Awaited<ReturnType<typeof cosmeticsGetAll>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof cosmeticsGetAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCosmeticsGetAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof cosmeticsGetAll>>> = ({ signal }) => cosmeticsGetAll({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cosmeticsGetAll>>, TError, TData> & { queryKey: QueryKey }
}

export type CosmeticsGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof cosmeticsGetAll>>>
export type CosmeticsGetAllQueryError = unknown


/**
 * @summary Retrieve all available cosmetics in the shop
 */

export function useCosmeticsGetAll<TData = Awaited<ReturnType<typeof cosmeticsGetAll>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof cosmeticsGetAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCosmeticsGetAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type cosmeticsBuyResponse200 = {
  data: GameProgress
  status: 200
}

export type cosmeticsBuyResponseSuccess = (cosmeticsBuyResponse200) & {
  headers: Headers;
};
;

export type cosmeticsBuyResponse = (cosmeticsBuyResponseSuccess)

export const getCosmeticsBuyUrl = () => {




  return `/user/cosmetics/buy`
}

/**
 * @summary Buy a cosmetic item
 */
export const cosmeticsBuy = async (cosmeticsBuyBody: CosmeticsBuyBody, options?: Parameters<typeof customInstance>[1]): Promise<cosmeticsBuyResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<cosmeticsBuyResponse>(getCosmeticsBuyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cosmeticsBuyBody)
  }
);}





export const getCosmeticsBuyMutationKey = () => ['cosmeticsBuy'] as const;

export const getCosmeticsBuyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cosmeticsBuy>>, TError,CosmeticsBuyMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cosmeticsBuy>>, TError,CosmeticsBuyMutationVariables, TContext> => {

const mutationKey = getCosmeticsBuyMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cosmeticsBuy>>, CosmeticsBuyMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  cosmeticsBuy(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CosmeticsBuyMutationResult = NonNullable<Awaited<ReturnType<typeof cosmeticsBuy>>>
    export type CosmeticsBuyMutationBody = CosmeticsBuyBody
    export type CosmeticsBuyMutationError = unknown
    export type CosmeticsBuyMutationVariables = {data: CosmeticsBuyBody}

    /**
 * @summary Buy a cosmetic item
 */
export const useCosmeticsBuy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cosmeticsBuy>>, TError,CosmeticsBuyMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof cosmeticsBuy>>,
        TError,
        CosmeticsBuyMutationVariables,
        TContext
      > => {
      return useMutation(getCosmeticsBuyMutationOptions(options));
    }

export type cosmeticsEquipResponse200 = {
  data: GameProgress
  status: 200
}

export type cosmeticsEquipResponseSuccess = (cosmeticsEquipResponse200) & {
  headers: Headers;
};
;

export type cosmeticsEquipResponse = (cosmeticsEquipResponseSuccess)

export const getCosmeticsEquipUrl = () => {




  return `/user/cosmetics/equip`
}

/**
 * @summary Equip or unequip a cosmetic item
 */
export const cosmeticsEquip = async (cosmeticsEquipBody: CosmeticsEquipBody, options?: Parameters<typeof customInstance>[1]): Promise<cosmeticsEquipResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customInstance<cosmeticsEquipResponse>(getCosmeticsEquipUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cosmeticsEquipBody)
  }
);}





export const getCosmeticsEquipMutationKey = () => ['cosmeticsEquip'] as const;

export const getCosmeticsEquipMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cosmeticsEquip>>, TError,CosmeticsEquipMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cosmeticsEquip>>, TError,CosmeticsEquipMutationVariables, TContext> => {

const mutationKey = getCosmeticsEquipMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cosmeticsEquip>>, CosmeticsEquipMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  cosmeticsEquip(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CosmeticsEquipMutationResult = NonNullable<Awaited<ReturnType<typeof cosmeticsEquip>>>
    export type CosmeticsEquipMutationBody = CosmeticsEquipBody
    export type CosmeticsEquipMutationError = unknown
    export type CosmeticsEquipMutationVariables = {data: CosmeticsEquipBody}

    /**
 * @summary Equip or unequip a cosmetic item
 */
export const useCosmeticsEquip = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cosmeticsEquip>>, TError,CosmeticsEquipMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof cosmeticsEquip>>,
        TError,
        CosmeticsEquipMutationVariables,
        TContext
      > => {
      return useMutation(getCosmeticsEquipMutationOptions(options));
    }

