/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hibrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Challenge,
  ChallengeRequest,
  ChallengeResultRequest,
  Credentials,
  CredentialsEmail,
  CredentialsPassword,
  GameProgress,
  Subscription,
  SubscriptionCreate,
  UserProfile,
} from "./model";

import { customInstance } from "../utils/api-client";

export type userForgottenResponse201 = {
  data: void;
  status: 201;
};

export type userForgottenResponseSuccess = userForgottenResponse201 & {
  headers: Headers;
};
export type userForgottenResponse = userForgottenResponseSuccess;

export const getUserForgottenUrl = () => {
  return `/user/forgotten`;
};

export const userForgotten = async (
  credentialsEmail: CredentialsEmail,
  options?: RequestInit,
): Promise<userForgottenResponse> => {
  return customInstance<userForgottenResponse>(getUserForgottenUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(credentialsEmail),
  });
};

export const getUserForgottenMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userForgotten>>,
    TError,
    { data: CredentialsEmail },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userForgotten>>,
  TError,
  { data: CredentialsEmail },
  TContext
> => {
  const mutationKey = ["userForgotten"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userForgotten>>,
    { data: CredentialsEmail }
  > = (props) => {
    const { data } = props ?? {};

    return userForgotten(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserForgottenMutationResult = NonNullable<
  Awaited<ReturnType<typeof userForgotten>>
>;
export type UserForgottenMutationBody = CredentialsEmail;
export type UserForgottenMutationError = unknown;

export const useUserForgotten = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userForgotten>>,
    TError,
    { data: CredentialsEmail },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userForgotten>>,
  TError,
  { data: CredentialsEmail },
  TContext
> => {
  return useMutation(getUserForgottenMutationOptions(options));
};

export type userLoginResponse200 = {
  data: UserProfile;
  status: 200;
};

export type userLoginResponseSuccess = userLoginResponse200 & {
  headers: Headers;
};
export type userLoginResponse = userLoginResponseSuccess;

export const getUserLoginUrl = () => {
  return `/user/login`;
};

/**
 * @summary check the credentials and login
 */
export const userLogin = async (
  credentials: Credentials,
  options?: RequestInit,
): Promise<userLoginResponse> => {
  return customInstance<userLoginResponse>(getUserLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(credentials),
  });
};

export const getUserLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userLogin>>,
    TError,
    { data: Credentials },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userLogin>>,
  TError,
  { data: Credentials },
  TContext
> => {
  const mutationKey = ["userLogin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userLogin>>,
    { data: Credentials }
  > = (props) => {
    const { data } = props ?? {};

    return userLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof userLogin>>
>;
export type UserLoginMutationBody = Credentials;
export type UserLoginMutationError = unknown;

/**
 * @summary check the credentials and login
 */
export const useUserLogin = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userLogin>>,
    TError,
    { data: Credentials },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userLogin>>,
  TError,
  { data: Credentials },
  TContext
> => {
  return useMutation(getUserLoginMutationOptions(options));
};

export type userLoginPasswordResponse200 = {
  data: UserProfile;
  status: 200;
};

export type userLoginPasswordResponseSuccess = userLoginPasswordResponse200 & {
  headers: Headers;
};
export type userLoginPasswordResponse = userLoginPasswordResponseSuccess;

export const getUserLoginPasswordUrl = () => {
  return `/user/login`;
};

/**
 * @summary submit new password after forgotten
 */
export const userLoginPassword = async (
  credentialsPassword: CredentialsPassword,
  options?: RequestInit,
): Promise<userLoginPasswordResponse> => {
  return customInstance<userLoginPasswordResponse>(getUserLoginPasswordUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(credentialsPassword),
  });
};

export const getUserLoginPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userLoginPassword>>,
    TError,
    { data: CredentialsPassword },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userLoginPassword>>,
  TError,
  { data: CredentialsPassword },
  TContext
> => {
  const mutationKey = ["userLoginPassword"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userLoginPassword>>,
    { data: CredentialsPassword }
  > = (props) => {
    const { data } = props ?? {};

    return userLoginPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserLoginPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof userLoginPassword>>
>;
export type UserLoginPasswordMutationBody = CredentialsPassword;
export type UserLoginPasswordMutationError = unknown;

/**
 * @summary submit new password after forgotten
 */
export const useUserLoginPassword = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userLoginPassword>>,
    TError,
    { data: CredentialsPassword },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userLoginPassword>>,
  TError,
  { data: CredentialsPassword },
  TContext
> => {
  return useMutation(getUserLoginPasswordMutationOptions(options));
};

export type userRegisterResponse200 = {
  data: UserProfile;
  status: 200;
};

export type userRegisterResponseSuccess = userRegisterResponse200 & {
  headers: Headers;
};
export type userRegisterResponse = userRegisterResponseSuccess;

export const getUserRegisterUrl = () => {
  return `/user/register`;
};

/**
 * @summary Register a new user
 */
export const userRegister = async (
  credentials: Credentials,
  options?: RequestInit,
): Promise<userRegisterResponse> => {
  return customInstance<userRegisterResponse>(getUserRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(credentials),
  });
};

export const getUserRegisterMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userRegister>>,
    TError,
    { data: Credentials },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userRegister>>,
  TError,
  { data: Credentials },
  TContext
> => {
  const mutationKey = ["userRegister"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userRegister>>,
    { data: Credentials }
  > = (props) => {
    const { data } = props ?? {};

    return userRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof userRegister>>
>;
export type UserRegisterMutationBody = Credentials;
export type UserRegisterMutationError = unknown;

/**
 * @summary Register a new user
 */
export const useUserRegister = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userRegister>>,
    TError,
    { data: Credentials },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userRegister>>,
  TError,
  { data: Credentials },
  TContext
> => {
  return useMutation(getUserRegisterMutationOptions(options));
};

export type userForgottenPasswordResponse201 = {
  data: void;
  status: 201;
};

export type userForgottenPasswordResponseSuccess =
  userForgottenPasswordResponse201 & {
    headers: Headers;
  };
export type userForgottenPasswordResponse =
  userForgottenPasswordResponseSuccess;

export const getUserForgottenPasswordUrl = () => {
  return `/user/forgotten-password`;
};

/**
 * @summary Send forgotten password email
 */
export const userForgottenPassword = async (
  credentialsEmail: CredentialsEmail,
  options?: RequestInit,
): Promise<userForgottenPasswordResponse> => {
  return customInstance<userForgottenPasswordResponse>(
    getUserForgottenPasswordUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(credentialsEmail),
    },
  );
};

export const getUserForgottenPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userForgottenPassword>>,
    TError,
    { data: CredentialsEmail },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userForgottenPassword>>,
  TError,
  { data: CredentialsEmail },
  TContext
> => {
  const mutationKey = ["userForgottenPassword"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userForgottenPassword>>,
    { data: CredentialsEmail }
  > = (props) => {
    const { data } = props ?? {};

    return userForgottenPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserForgottenPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof userForgottenPassword>>
>;
export type UserForgottenPasswordMutationBody = CredentialsEmail;
export type UserForgottenPasswordMutationError = unknown;

/**
 * @summary Send forgotten password email
 */
export const useUserForgottenPassword = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userForgottenPassword>>,
    TError,
    { data: CredentialsEmail },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userForgottenPassword>>,
  TError,
  { data: CredentialsEmail },
  TContext
> => {
  return useMutation(getUserForgottenPasswordMutationOptions(options));
};

export type challengeStartNewResponse200 = {
  data: Challenge;
  status: 200;
};

export type challengeStartNewResponseSuccess = challengeStartNewResponse200 & {
  headers: Headers;
};
export type challengeStartNewResponse = challengeStartNewResponseSuccess;

export const getChallengeStartNewUrl = (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
) => {
  return `/Challenges/${operationId}`;
};

/**
 * @summary Create a new game
 */
export const challengeStartNew = async (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  challengeRequest: ChallengeRequest,
  options?: RequestInit,
): Promise<challengeStartNewResponse> => {
  return customInstance<challengeStartNewResponse>(
    getChallengeStartNewUrl(operationId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(challengeRequest),
    },
  );
};

export const getChallengeStartNewMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof challengeStartNew>>,
    TError,
    {
      operationId: "addition" | "subtraction" | "multiplication" | "division+";
      data: ChallengeRequest;
    },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof challengeStartNew>>,
  TError,
  {
    operationId: "addition" | "subtraction" | "multiplication" | "division+";
    data: ChallengeRequest;
  },
  TContext
> => {
  const mutationKey = ["challengeStartNew"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof challengeStartNew>>,
    {
      operationId: "addition" | "subtraction" | "multiplication" | "division+";
      data: ChallengeRequest;
    }
  > = (props) => {
    const { operationId, data } = props ?? {};

    return challengeStartNew(operationId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChallengeStartNewMutationResult = NonNullable<
  Awaited<ReturnType<typeof challengeStartNew>>
>;
export type ChallengeStartNewMutationBody = ChallengeRequest;
export type ChallengeStartNewMutationError = unknown;

/**
 * @summary Create a new game
 */
export const useChallengeStartNew = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof challengeStartNew>>,
    TError,
    {
      operationId: "addition" | "subtraction" | "multiplication" | "division+";
      data: ChallengeRequest;
    },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof challengeStartNew>>,
  TError,
  {
    operationId: "addition" | "subtraction" | "multiplication" | "division+";
    data: ChallengeRequest;
  },
  TContext
> => {
  return useMutation(getChallengeStartNewMutationOptions(options));
};

export type challengeGetAllResponse200 = {
  data: Challenge;
  status: 200;
};

export type challengeGetAllResponseSuccess = challengeGetAllResponse200 & {
  headers: Headers;
};
export type challengeGetAllResponse = challengeGetAllResponseSuccess;

export const getChallengeGetAllUrl = (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
) => {
  return `/Challenges/${operationId}`;
};

/**
 * @summary Get all user Challenges
 */
export const challengeGetAll = async (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  options?: RequestInit,
): Promise<challengeGetAllResponse> => {
  return customInstance<challengeGetAllResponse>(
    getChallengeGetAllUrl(operationId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getChallengeGetAllQueryKey = (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
) => {
  return [`/Challenges/${operationId}`] as const;
};

export const getChallengeGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof challengeGetAll>>,
  TError = unknown,
>(
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof challengeGetAll>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getChallengeGetAllQueryKey(operationId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof challengeGetAll>>> = ({
    signal,
  }) => challengeGetAll(operationId, { signal });

  return {
    queryKey,
    queryFn,
    enabled: operationId !== null && operationId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof challengeGetAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ChallengeGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof challengeGetAll>>
>;
export type ChallengeGetAllQueryError = unknown;

/**
 * @summary Get all user Challenges
 */

export function useChallengeGetAll<
  TData = Awaited<ReturnType<typeof challengeGetAll>>,
  TError = unknown,
>(
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof challengeGetAll>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getChallengeGetAllQueryOptions(operationId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type challengeGetResponse200 = {
  data: Challenge;
  status: 200;
};

export type challengeGetResponseSuccess = challengeGetResponse200 & {
  headers: Headers;
};
export type challengeGetResponse = challengeGetResponseSuccess;

export const getChallengeGetUrl = (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  id: string,
) => {
  return `/chaleges/${operationId}/${id}`;
};

/**
 * @summary Get Challenge by id
 */
export const challengeGet = async (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  id: string,
  options?: RequestInit,
): Promise<challengeGetResponse> => {
  return customInstance<challengeGetResponse>(
    getChallengeGetUrl(operationId, id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getChallengeGetQueryKey = (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  id: string,
) => {
  return [`/chaleges/${operationId}/${id}`] as const;
};

export const getChallengeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof challengeGet>>,
  TError = unknown,
>(
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof challengeGet>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getChallengeGetQueryKey(operationId, id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof challengeGet>>> = ({
    signal,
  }) => challengeGet(operationId, id, { signal });

  return {
    queryKey,
    queryFn,
    enabled:
      operationId !== null &&
      operationId !== undefined &&
      id !== null &&
      id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof challengeGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ChallengeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof challengeGet>>
>;
export type ChallengeGetQueryError = unknown;

/**
 * @summary Get Challenge by id
 */

export function useChallengeGet<
  TData = Awaited<ReturnType<typeof challengeGet>>,
  TError = unknown,
>(
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof challengeGet>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getChallengeGetQueryOptions(operationId, id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type challengeUpdateResultResponse200 = {
  data: GameProgress;
  status: 200;
};

export type challengeUpdateResultResponseSuccess =
  challengeUpdateResultResponse200 & {
    headers: Headers;
  };
export type challengeUpdateResultResponse =
  challengeUpdateResultResponseSuccess;

export const getChallengeUpdateResultUrl = (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  id: string,
) => {
  return `/chaleges/${operationId}/${id}`;
};

/**
 * @summary Update Challenge items
 */
export const challengeUpdateResult = async (
  operationId: "addition" | "subtraction" | "multiplication" | "division+",
  id: string,
  challengeResultRequest: ChallengeResultRequest,
  options?: RequestInit,
): Promise<challengeUpdateResultResponse> => {
  return customInstance<challengeUpdateResultResponse>(
    getChallengeUpdateResultUrl(operationId, id),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(challengeResultRequest),
    },
  );
};

export const getChallengeUpdateResultMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof challengeUpdateResult>>,
    TError,
    {
      operationId: "addition" | "subtraction" | "multiplication" | "division+";
      id: string;
      data: ChallengeResultRequest;
    },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof challengeUpdateResult>>,
  TError,
  {
    operationId: "addition" | "subtraction" | "multiplication" | "division+";
    id: string;
    data: ChallengeResultRequest;
  },
  TContext
> => {
  const mutationKey = ["challengeUpdateResult"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof challengeUpdateResult>>,
    {
      operationId: "addition" | "subtraction" | "multiplication" | "division+";
      id: string;
      data: ChallengeResultRequest;
    }
  > = (props) => {
    const { operationId, id, data } = props ?? {};

    return challengeUpdateResult(operationId, id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChallengeUpdateResultMutationResult = NonNullable<
  Awaited<ReturnType<typeof challengeUpdateResult>>
>;
export type ChallengeUpdateResultMutationBody = ChallengeResultRequest;
export type ChallengeUpdateResultMutationError = unknown;

/**
 * @summary Update Challenge items
 */
export const useChallengeUpdateResult = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof challengeUpdateResult>>,
    TError,
    {
      operationId: "addition" | "subtraction" | "multiplication" | "division+";
      id: string;
      data: ChallengeResultRequest;
    },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof challengeUpdateResult>>,
  TError,
  {
    operationId: "addition" | "subtraction" | "multiplication" | "division+";
    id: string;
    data: ChallengeResultRequest;
  },
  TContext
> => {
  return useMutation(getChallengeUpdateResultMutationOptions(options));
};

export type subscribtionUpdateResponse200 = {
  data: Subscription;
  status: 200;
};

export type subscribtionUpdateResponseSuccess =
  subscribtionUpdateResponse200 & {
    headers: Headers;
  };
export type subscribtionUpdateResponse = subscribtionUpdateResponseSuccess;

export const getSubscribtionUpdateUrl = () => {
  return `/subscribtions`;
};

/**
 * @summary Add new subscribtion
 */
export const subscribtionUpdate = async (
  subscriptionCreate: SubscriptionCreate,
  options?: RequestInit,
): Promise<subscribtionUpdateResponse> => {
  return customInstance<subscribtionUpdateResponse>(
    getSubscribtionUpdateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(subscriptionCreate),
    },
  );
};

export const getSubscribtionUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscribtionUpdate>>,
    TError,
    { data: SubscriptionCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof subscribtionUpdate>>,
  TError,
  { data: SubscriptionCreate },
  TContext
> => {
  const mutationKey = ["subscribtionUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof subscribtionUpdate>>,
    { data: SubscriptionCreate }
  > = (props) => {
    const { data } = props ?? {};

    return subscribtionUpdate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubscribtionUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof subscribtionUpdate>>
>;
export type SubscribtionUpdateMutationBody = SubscriptionCreate;
export type SubscribtionUpdateMutationError = unknown;

/**
 * @summary Add new subscribtion
 */
export const useSubscribtionUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscribtionUpdate>>,
    TError,
    { data: SubscriptionCreate },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof subscribtionUpdate>>,
  TError,
  { data: SubscriptionCreate },
  TContext
> => {
  return useMutation(getSubscribtionUpdateMutationOptions(options));
};

export type subscribtionCancelImediatellyResponse200 = {
  data: void;
  status: 200;
};

export type subscribtionCancelImediatellyResponseSuccess =
  subscribtionCancelImediatellyResponse200 & {
    headers: Headers;
  };
export type subscribtionCancelImediatellyResponse =
  subscribtionCancelImediatellyResponseSuccess;

export const getSubscribtionCancelImediatellyUrl = () => {
  return `/subscribtions`;
};

/**
 * @summary Remove subscribtion
 */
export const subscribtionCancelImediatelly = async (
  options?: RequestInit,
): Promise<subscribtionCancelImediatellyResponse> => {
  return customInstance<subscribtionCancelImediatellyResponse>(
    getSubscribtionCancelImediatellyUrl(),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getSubscribtionCancelImediatellyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscribtionCancelImediatelly>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof subscribtionCancelImediatelly>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["subscribtionCancelImediatelly"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof subscribtionCancelImediatelly>>,
    void
  > = () => {
    return subscribtionCancelImediatelly();
  };

  return { mutationFn, ...mutationOptions };
};

export type SubscribtionCancelImediatellyMutationResult = NonNullable<
  Awaited<ReturnType<typeof subscribtionCancelImediatelly>>
>;

export type SubscribtionCancelImediatellyMutationError = unknown;

/**
 * @summary Remove subscribtion
 */
export const useSubscribtionCancelImediatelly = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscribtionCancelImediatelly>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof subscribtionCancelImediatelly>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getSubscribtionCancelImediatellyMutationOptions(options));
};

export type gameProgressResponse200 = {
  data: GameProgress;
  status: 200;
};

export type gameProgressResponseSuccess = gameProgressResponse200 & {
  headers: Headers;
};
export type gameProgressResponse = gameProgressResponseSuccess;

export const getGameProgressUrl = () => {
  return `/game/progress`;
};

/**
 * @summary Get game status
 */
export const gameProgress = async (
  options?: RequestInit,
): Promise<gameProgressResponse> => {
  return customInstance<gameProgressResponse>(getGameProgressUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGameProgressQueryKey = () => {
  return [`/game/progress`] as const;
};

export const getGameProgressQueryOptions = <
  TData = Awaited<ReturnType<typeof gameProgress>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof gameProgress>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGameProgressQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof gameProgress>>> = ({
    signal,
  }) => gameProgress({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof gameProgress>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GameProgressQueryResult = NonNullable<
  Awaited<ReturnType<typeof gameProgress>>
>;
export type GameProgressQueryError = unknown;

/**
 * @summary Get game status
 */

export function useGameProgress<
  TData = Awaited<ReturnType<typeof gameProgress>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof gameProgress>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGameProgressQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
