/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import { z as zod } from 'zod';

export const Challenge = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division', 'gauntlet', 'daily_challenge']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.string().uuid().optional(),
  "challengeId": zod.string().uuid().optional()
}).and(zod.object({
  "result": zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
}).optional(),
  "id": zod.string().uuid().optional(),
  "exercises": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "maxTime": zod.number().optional(),
  "xpOnSuccess": zod.number().optional(),
  "xpOnFailure": zod.number().optional(),
  "coinsOnSuccess": zod.number().optional(),
  "coinsOnFailure": zod.number().optional(),
  "coins": zod.number().optional(),
  "allowedMistakes": zod.number().optional()
}))

type Challenge = zod.input<typeof Challenge>;
type ChallengeOutput = zod.output<typeof Challenge>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const ChallengeRequest = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division', 'gauntlet', 'daily_challenge']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.string().uuid().optional(),
  "challengeId": zod.string().uuid().optional()
})

type ChallengeRequest = zod.input<typeof ChallengeRequest>;
type ChallengeRequestOutput = zod.output<typeof ChallengeRequest>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const ChallengeResultRequest = zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
})

type ChallengeResultRequest = zod.input<typeof ChallengeResultRequest>;
type ChallengeResultRequestOutput = zod.output<typeof ChallengeResultRequest>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const ChallengeStartNewBody = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division', 'gauntlet', 'daily_challenge']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.string().uuid().optional(),
  "challengeId": zod.string().uuid().optional()
})

type ChallengeStartNewBody = zod.input<typeof ChallengeStartNewBody>;
type ChallengeStartNewBodyOutput = zod.output<typeof ChallengeStartNewBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const ChallengeUpdateResultBody = zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
})

type ChallengeUpdateResultBody = zod.input<typeof ChallengeUpdateResultBody>;
type ChallengeUpdateResultBodyOutput = zod.output<typeof ChallengeUpdateResultBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const Cosmetic = zod.object({
  "id": zod.string().uuid().optional(),
  "name": zod.string().optional(),
  "type": zod.enum(['cape', 'suit', 'flare']).optional(),
  "price": zod.number().optional(),
  "assetId": zod.string().optional(),
  "requiredLevel": zod.number().optional()
})

type Cosmetic = zod.input<typeof Cosmetic>;
type CosmeticOutput = zod.output<typeof Cosmetic>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const CosmeticsBuyBody = zod.object({
  "cosmeticId": zod.string().uuid()
})

type CosmeticsBuyBody = zod.input<typeof CosmeticsBuyBody>;
type CosmeticsBuyBodyOutput = zod.output<typeof CosmeticsBuyBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const CosmeticsEquipBody = zod.object({
  "cosmeticId": zod.string().uuid(),
  "equipped": zod.boolean()
})

type CosmeticsEquipBody = zod.input<typeof CosmeticsEquipBody>;
type CosmeticsEquipBodyOutput = zod.output<typeof CosmeticsEquipBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const Credentials = zod.object({
  "email": zod.string().email()
}).and(zod.object({
  "password": zod.string()
}))

type Credentials = zod.input<typeof Credentials>;
type CredentialsOutput = zod.output<typeof Credentials>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const CredentialsEmail = zod.object({
  "email": zod.string().email().optional()
})

type CredentialsEmail = zod.input<typeof CredentialsEmail>;
type CredentialsEmailOutput = zod.output<typeof CredentialsEmail>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const CredentialsPassword = zod.object({
  "password": zod.string().optional()
})

type CredentialsPassword = zod.input<typeof CredentialsPassword>;
type CredentialsPasswordOutput = zod.output<typeof CredentialsPassword>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const EquationType = zod.enum(['entry', 'result', 'operator'])

type EquationType = zod.input<typeof EquationType>;
type EquationTypeOutput = zod.output<typeof EquationType>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const Exercise = zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})

type Exercise = zod.input<typeof Exercise>;
type ExerciseOutput = zod.output<typeof Exercise>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const ForgottenCredentials = zod.object({
  "password": zod.string()
}).and(zod.object({
  "tokenForgotten": zod.string()
}))

type ForgottenCredentials = zod.input<typeof ForgottenCredentials>;
type ForgottenCredentialsOutput = zod.output<typeof ForgottenCredentials>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const ForgottenToken = zod.object({
  "tokenForgotten": zod.string().optional()
})

type ForgottenToken = zod.input<typeof ForgottenToken>;
type ForgottenTokenOutput = zod.output<typeof ForgottenToken>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const GameOperationProgress = zod.object({
  "level": zod.number().optional(),
  "xp": zod.number().optional(),
  "challenges": zod.array(zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division', 'gauntlet', 'daily_challenge']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.string().uuid().optional(),
  "challengeId": zod.string().uuid().optional()
}).and(zod.object({
  "result": zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
}).optional(),
  "id": zod.string().uuid().optional(),
  "exercises": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "maxTime": zod.number().optional(),
  "xpOnSuccess": zod.number().optional(),
  "xpOnFailure": zod.number().optional(),
  "coinsOnSuccess": zod.number().optional(),
  "coinsOnFailure": zod.number().optional(),
  "coins": zod.number().optional(),
  "allowedMistakes": zod.number().optional()
}))).optional()
})

type GameOperationProgress = zod.input<typeof GameOperationProgress>;
type GameOperationProgressOutput = zod.output<typeof GameOperationProgress>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const GameProgress = zod.object({
  "level": zod.number().optional(),
  "xp": zod.number().optional(),
  "coins": zod.number().optional(),
  "operations": zod.array(zod.object({
  "level": zod.number().optional(),
  "xp": zod.number().optional(),
  "challenges": zod.array(zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division', 'gauntlet', 'daily_challenge']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.string().uuid().optional(),
  "challengeId": zod.string().uuid().optional()
}).and(zod.object({
  "result": zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
}).optional(),
  "id": zod.string().uuid().optional(),
  "exercises": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "maxTime": zod.number().optional(),
  "xpOnSuccess": zod.number().optional(),
  "xpOnFailure": zod.number().optional(),
  "coinsOnSuccess": zod.number().optional(),
  "coinsOnFailure": zod.number().optional(),
  "coins": zod.number().optional(),
  "allowedMistakes": zod.number().optional()
}))).optional()
})).optional(),
  "purchasedCosmetics": zod.array(zod.string().uuid()).optional(),
  "equippedCape": zod.string().uuid().nullish(),
  "equippedSuit": zod.string().uuid().nullish(),
  "equippedFlare": zod.string().uuid().nullish(),
  "minigameProgress": zod.array(zod.object({
  "minigameId": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "level": zod.number().optional(),
  "xp": zod.number().optional()
})).optional()
})

type GameProgress = zod.input<typeof GameProgress>;
type GameProgressOutput = zod.output<typeof GameProgress>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const Id = zod.string().uuid()

type Id = zod.input<typeof Id>;
type IdOutput = zod.output<typeof Id>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */

































/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const Minigame = zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory'])

type Minigame = zod.input<typeof Minigame>;
type MinigameOutput = zod.output<typeof Minigame>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const MinigameProgress = zod.object({
  "minigameId": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "level": zod.number().optional(),
  "xp": zod.number().optional()
})

type MinigameProgress = zod.input<typeof MinigameProgress>;
type MinigameProgressOutput = zod.output<typeof MinigameProgress>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const OperationId = zod.enum(['addition', 'subtraction', 'multiplication', 'division', 'gauntlet', 'daily_challenge'])

type OperationId = zod.input<typeof OperationId>;
type OperationIdOutput = zod.output<typeof OperationId>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const Subscription = zod.object({
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
}).and(zod.object({
  "id": zod.string().uuid().optional(),
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
}))

type Subscription = zod.input<typeof Subscription>;
type SubscriptionOutput = zod.output<typeof Subscription>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const SubscriptionCreate = zod.object({
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
})

type SubscriptionCreate = zod.input<typeof SubscriptionCreate>;
type SubscriptionCreateOutput = zod.output<typeof SubscriptionCreate>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const SubscriptionType = zod.enum(['addsFree', 'full'])

type SubscriptionType = zod.input<typeof SubscriptionType>;
type SubscriptionTypeOutput = zod.output<typeof SubscriptionType>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const SubscriptionUpdateBody = zod.object({
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
})

type SubscriptionUpdateBody = zod.input<typeof SubscriptionUpdateBody>;
type SubscriptionUpdateBodyOutput = zod.output<typeof SubscriptionUpdateBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const UserForgottenBody = zod.object({
  "email": zod.string().email().optional()
})

type UserForgottenBody = zod.input<typeof UserForgottenBody>;
type UserForgottenBodyOutput = zod.output<typeof UserForgottenBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const UserForgottenPasswordBody = zod.object({
  "email": zod.string().email().optional()
})

type UserForgottenPasswordBody = zod.input<typeof UserForgottenPasswordBody>;
type UserForgottenPasswordBodyOutput = zod.output<typeof UserForgottenPasswordBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const UserLoginBody = zod.object({
  "email": zod.string().email()
}).and(zod.object({
  "password": zod.string()
}))

type UserLoginBody = zod.input<typeof UserLoginBody>;
type UserLoginBodyOutput = zod.output<typeof UserLoginBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const UserLoginPasswordBody = zod.object({
  "password": zod.string().optional()
})

type UserLoginPasswordBody = zod.input<typeof UserLoginPasswordBody>;
type UserLoginPasswordBodyOutput = zod.output<typeof UserLoginPasswordBody>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const UserProfile = zod.object({
  "id": zod.string().uuid().optional(),
  "name": zod.string().optional(),
  "subscription": zod.object({
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
}).and(zod.object({
  "id": zod.string().uuid().optional(),
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
})).optional()
})

type UserProfile = zod.input<typeof UserProfile>;
type UserProfileOutput = zod.output<typeof UserProfile>;

/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */


export const UserRegisterBody = zod.object({
  "email": zod.string().email()
}).and(zod.object({
  "password": zod.string()
}))

type UserRegisterBody = zod.input<typeof UserRegisterBody>;
type UserRegisterBodyOutput = zod.output<typeof UserRegisterBody>;
