/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Cyberspace-api
 * Hybrid game api to access databases
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';


export const UserForgottenBody = zod.object({
  "email": zod.email().optional()
})

export const UserForgottenResponse = zod.void()


/**
 * @summary check the credentials and login
 */
export const UserLoginBody = zod.object({
  "email": zod.email()
}).and(zod.object({
  "password": zod.string()
}))

export const UserLoginResponse = zod.object({
  "id": zod.uuid().optional(),
  "name": zod.string().optional(),
  "subscription": zod.object({
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
}).and(zod.object({
  "id": zod.uuid().optional(),
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
})).optional()
})


/**
 * @summary submit new password after forgotten
 */
export const UserLoginPasswordBody = zod.object({
  "password": zod.string().optional()
})

export const UserLoginPasswordResponse = zod.object({
  "id": zod.uuid().optional(),
  "name": zod.string().optional(),
  "subscription": zod.object({
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
}).and(zod.object({
  "id": zod.uuid().optional(),
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
})).optional()
})


/**
 * @summary Register a new user
 */
export const UserRegisterBody = zod.object({
  "email": zod.email()
}).and(zod.object({
  "password": zod.string()
}))

export const UserRegisterResponse = zod.unknown()


/**
 * @summary Send forgotten password email
 */
export const UserForgottenPasswordBody = zod.object({
  "email": zod.email().optional()
})

export const UserForgottenPasswordResponse = zod.void()


/**
 * @summary Create a new game
 */
export const ChallengeStartNewParams = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).describe('Operation to filter by')
})

export const ChallengeStartNewBody = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.uuid().optional(),
  "challengeId": zod.uuid().optional()
})

export const ChallengeStartNewResponse = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.uuid().optional(),
  "challengeId": zod.uuid().optional()
}).and(zod.object({
  "result": zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
}).optional(),
  "id": zod.uuid().optional(),
  "exercises": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "maxTime": zod.number().optional(),
  "xpOnSuccess": zod.number().optional(),
  "xpOnFailure": zod.number().optional(),
  "coinsOnSuccess": zod.number().optional(),
  "coinsOnFailure": zod.number().optional(),
  "coins": zod.number().optional(),
  "allowedMistakes": zod.number().optional()
}))


/**
 * @summary Get all user challenges
 */
export const ChallengeGetAllParams = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).describe('Operation to filter by')
})

export const ChallengeGetAllResponse = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.uuid().optional(),
  "challengeId": zod.uuid().optional()
}).and(zod.object({
  "result": zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
}).optional(),
  "id": zod.uuid().optional(),
  "exercises": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "maxTime": zod.number().optional(),
  "xpOnSuccess": zod.number().optional(),
  "xpOnFailure": zod.number().optional(),
  "coinsOnSuccess": zod.number().optional(),
  "coinsOnFailure": zod.number().optional(),
  "coins": zod.number().optional(),
  "allowedMistakes": zod.number().optional()
}))


/**
 * @summary Get challenge by id
 */
export const ChallengeGetParams = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).describe('Operation to filter by'),
  "id": zod.uuid().describe('Unique identifier of a challenge session or user')
})

export const ChallengeGetResponse = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.uuid().optional(),
  "challengeId": zod.uuid().optional()
}).and(zod.object({
  "result": zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
}).optional(),
  "id": zod.uuid().optional(),
  "exercises": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "maxTime": zod.number().optional(),
  "xpOnSuccess": zod.number().optional(),
  "xpOnFailure": zod.number().optional(),
  "coinsOnSuccess": zod.number().optional(),
  "coinsOnFailure": zod.number().optional(),
  "coins": zod.number().optional(),
  "allowedMistakes": zod.number().optional()
}))


/**
 * @summary Update challenge items
 */
export const ChallengeUpdateResultParams = zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).describe('Operation to filter by'),
  "id": zod.uuid().describe('Unique identifier of a challenge session or user')
})

export const ChallengeUpdateResultBody = zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
})

export const ChallengeUpdateResultResponse = zod.object({
  "level": zod.number().optional(),
  "xp": zod.number().optional(),
  "coins": zod.number().optional(),
  "operations": zod.array(zod.object({
  "level": zod.number().optional(),
  "xp": zod.number().optional(),
  "challenges": zod.array(zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.uuid().optional(),
  "challengeId": zod.uuid().optional()
}).and(zod.object({
  "result": zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
}).optional(),
  "id": zod.uuid().optional(),
  "exercises": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "maxTime": zod.number().optional(),
  "xpOnSuccess": zod.number().optional(),
  "xpOnFailure": zod.number().optional(),
  "coinsOnSuccess": zod.number().optional(),
  "coinsOnFailure": zod.number().optional(),
  "coins": zod.number().optional(),
  "allowedMistakes": zod.number().optional()
}))).optional()
})).optional()
})


/**
 * @summary Add new subscription
 */
export const SubscriptionUpdateBody = zod.object({
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
})

export const SubscriptionUpdateResponse = zod.object({
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
}).and(zod.object({
  "id": zod.uuid().optional(),
  "type": zod.enum(['addsFree', 'full']).optional(),
  "autoRenew": zod.boolean().optional()
}))


/**
 * @summary Remove subscription
 */
export const SubscriptionCancelImmediatelyResponse = zod.unknown()


/**
 * @summary Get game status
 */
export const GameProgressResponse = zod.object({
  "level": zod.number().optional(),
  "xp": zod.number().optional(),
  "coins": zod.number().optional(),
  "operations": zod.array(zod.object({
  "level": zod.number().optional(),
  "xp": zod.number().optional(),
  "challenges": zod.array(zod.object({
  "operationId": zod.enum(['addition', 'subtraction', 'multiplication', 'division']).optional(),
  "minigame": zod.enum(['singleLine', 'dragAndDrop', 'crossNumbers', 'memory']).optional(),
  "userId": zod.uuid().optional(),
  "challengeId": zod.uuid().optional()
}).and(zod.object({
  "result": zod.object({
  "time": zod.number().optional(),
  "results": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "correctAnswers": zod.number().optional(),
  "coins": zod.number().optional(),
  "xp": zod.number().optional()
}).optional(),
  "id": zod.uuid().optional(),
  "exercises": zod.array(zod.object({
  "values": zod.array(zod.number()).optional(),
  "result": zod.number().optional(),
  "separator": zod.string().optional(),
  "userInput": zod.string().optional()
})).optional(),
  "maxTime": zod.number().optional(),
  "xpOnSuccess": zod.number().optional(),
  "xpOnFailure": zod.number().optional(),
  "coinsOnSuccess": zod.number().optional(),
  "coinsOnFailure": zod.number().optional(),
  "coins": zod.number().optional(),
  "allowedMistakes": zod.number().optional()
}))).optional()
})).optional()
})


