name: Deploy Expo App

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: mathematador-app
        run: npm install

      - name: Build the app
        working-directory: mathematador-app
        run: npm run build
      
      - name: Install server dependencies
        working-directory: server
        run: npm install
      
      - name: Build the server
        working-directory: server
        run: npm run build

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy dist folder to server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        working-directory: mathematador-app
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -r ./dist/* \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}
      
      - name: Copy server build to server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        working-directory: server
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -r ./build/* \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH_SERVER }}
      
      - name: copy server package-lock.json to server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        working-directory: server
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -r ./package-lock.json \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH_SERVER }}

      - name: copy server package.json to server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        working-directory: server
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -r ./package.json \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH_SERVER }}
            
      - name: Install server dependencies on server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd ${{ secrets.DEPLOY_PATH_SERVER }}
            npm ci
          "

      - name: Restart PM2 client process
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            pm2 restart ${{ secrets.PM2_APP_NAME }}
          "
      
      - name: Restart PM2 server process
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            pm2 restart ${{ secrets.PM2_SERVER_NAME }}
          "

